
server.port: 8084
app.name: myconfigproject
greating.message: Hello from yml to ${app.name}
my:
 list: abc, xyz, uvw
 dbvalues.as.object: "{connectionUrl: 'http://testconnectionurl', username:'foo', password:'pass'}"

db:
 connection: http://url
 host: dbhost
 port: 8525

management.endpoints.web.exposure.include: "*"
