server:port: 8084
app.name: io.ms.config.client
greating.message: Hello from ${app.name}
my:
 list: abc, xyz, uvw
 dbvalues.as.object: "{connectionUrl: 'http://localgiturl', username:'foo', password:'pass'}"

db:
 connection: "updated http://thisislocalgitdburl.spring-config.client-test"
 host: dblocalgithost.spring-config.client-test
 port: 8525

management.endpoints.web.exposure.include: "*"
#http://localhost:8080/actuator/configprops
